services:
#    nginx:
#        build:
#          context: ./.docker/nginx
#        container_name: acb-nginx
#        volumes:
#            - .:/var/www:rw
#            - ./logs/nginx:/var/log/nginx/:rw
#        ports:
#            - "80:80"
#        restart: unless-stopped
#        depends_on:
#            - php
#        networks:
#            - async-php-network

    php:
        build:
          context: ./.docker/php
          target: base
          args:
            - PUID=${PUID}
            - PGID=${PGID}
            - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        container_name: acb-php
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        depends_on:
            - redis
            - postgres
        volumes:
            - .:/var/www
        networks:
            - async-php-network

    postgres:
        build:
          context: ./.docker/postgres
        container_name: acb-postgres
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
        volumes:
            - db_data:/var/lib/postgresql/data:rw
          # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
          # - ./docker/db/data:/var/lib/postgresql/data:rw
        networks:
            - async-php-network

    redis:
        image: redis:alpine
        container_name: acb-redis
        restart: unless-stopped
        volumes:
            - redis_data:/var/lib/redis/data:rw
        networks:
            - async-php-network

volumes:
  db_data:
  redis_data:

networks:
    async-php-network:
        external: true